server:
  port: 8888
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    region: default
    service-url:
      default-zone: http://localhost:8761/eureka
